#!/usr/bin/env bash
# Example: type on the Windows PC from bash.
#
#   1. one-time setup:  bash btkbd.sh up  &&  bash btkbd.sh pair
#   2. focus Notepad (or any text field) on the PC
#   3. bash demo.sh

set -u
source "$(dirname "$0")/btkbd.sh"

btkbd_require_connected || {
  echo "not connected - run: bash $(dirname "$0")/btkbd.sh doctor" >&2
  exit 1
}

send_text "This text was generated by AI."
send_key ENTER
send_text "Typing through Bluetooth HID."

# a few more things you can do:
#
# send_key ENTER
# send_key CTRL+A                 # select all
# send_key CTRL+C                 # copy
# send_key ALT+TAB                # switch window
# send_key WIN+R                  # Run dialog
# send_key CTRL+SHIFT+ESC         # Task Manager
# send_key F5
# send_text $'line one\nline two' # \n becomes ENTER
# send_raw  0200040000000000      # raw report: SHIFT+a down
# send_raw  0000000000000000       # raw report: all keys up
